### PR TITLE
Implemented sending by Ctrl+Enter

### LINKED ISSUE #115: [Feature Request] Add support for sending message by Ctrl+Enter
It would be nice to have this feature.

### PR DESCRIPTION
**Pull request by Sollex-21412**
fixes #115

### CODE REVIEW

**Comment by realbardia** [comment]
Wow... It's awesome. Thank You :)

**Comment by Simulacrux** [comment]
THX, means this also, that a normal "Enter" while typing a message leads to a line feed in the message?

**Comment by Sollex-21412** [comment]
Yep (when ctrl+enter set) ;)

**Comment by Simulacrux** [comment]
Awesome. THX a lot.

**Comment by Sollex-21412** [comment]
linefeed

**Pull request merged**
